### ISSUE TITLE
Create pop-up component

### ISSUE THREAD

**Issue by jkbkupczyk** [bycza-zagroda/track-expenses-app-frontend#13]
Create an [**_pop-up component_**](https://material.angular.io/components/menu/overview)

![pop-up](https://user-images.githubusercontent.com/69753899/193105189-38099e4c-67ea-4799-9b95-0b1238bd786b.png)

**Make sure you use [angular material components](https://material.angular.io/components/categories)!**

1. Requirements
  Popup component must:
    - be able to contain _**any**_ text content
    - contain _**YES**_ button which will trigger the action function
    - contain _**CANCEL**_ button which will **_cancel_** and **_close_** popup

2. Example
`
<pop-up
        [text]="Are you sure to delete /"{{walletName}}/" and all related data?"
        (action)="deleteWallet(walletId)"></pop-up>
`

3. Tips
    - Use HTML5 tags with semantic meaning e.x. _dialog_ or _aside_ (I would use _aside_ if you ask me 😉)

**Comment by monikaRegula** [comment]
I take this issue, can you assign me @jkbkupczyk ?
