### ISSUE TITLE
Investigate partially failing Netlify deploy

### ISSUE THREAD

**Issue by purbanski-deftcode** [bycza-zagroda/track-expenses-app-frontend#145]
https://github.com/bycza-zagroda/track-expenses-app-frontend/pull/144
Deploy is partially failing but works in the end. Investigate why this is happening now.

**Comment by AdrianRomanski** [comment]
@Iwona007 @mirekgab Please check that issue

**Comment by mirekgab** [comment]
The problem was solved by change in netlify configuration.
