### ISSUE TITLE
Deleting wallet's transactions

### ISSUE THREAD

**Issue by purbanski-deftcode** [bycza-zagroda/track-expenses-app-frontend#62]
bycza-zagroda/story#2

First issue for transactions overview needs to be closed https://github.com/bycza-zagroda/track-expenses-app-frontend/issues/58.

We should be able to delete wallet's transaction by clicking on `Remove` button:
![transactions drawio - diagrams net 2022-12-27 09-14-01](https://user-images.githubusercontent.com/16034577/209639508-394c854c-ef5c-40bd-98bf-0d69236914a4.jpg)

# Requirements
- When clicking on `Remove` button we should display confirmation modal to confirm if we really want to do that
- We should also show loading indicator for request and success / error notifications if request will finish / fail

Information about the request can be found here https://bycza-zagroda.github.io/track-expenses-app-documentation/#/Transactions/deleteTransaction

**Comment by purbanski-deftcode** [comment]
Przypisane do DawidS.

**Comment by purbanski-deftcode** [comment]
Blocked by code changes in #61

**Comment by tomektomek321** [comment]
Mój tasek ( :
